version: '3.8'

services:
  #  Redis 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Node.js Frontend
  frontend:
    build: ./node-app
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./downloads:/downloads

  #  Go Backend Worker downloader
  worker:
    build: ./go-worker
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./downloads:/downloads